import turtle
import random
import time

bullet_list = []

window = turtle.Screen()
window.setup(1.0, 1.0)
window.bgcolor('black')
window.tracer(0)
so = turtle.Turtle()
so.hideturtle()
so.turtlesize(2)
so.color('yellow')
so.fillcolor('yellow')
so.shape('square')
so.left(45)
so.penup()
so.setposition(0, -310)
so.showturtle()
enemy = turtle.Turtle()
enemy.hideturtle()
enemy.turtlesize(1.3)
enemy.color('red')
enemy.fillcolor('red')
enemy.shape('square')
enemy.penup()
enemy.setposition(0, 310)
enemy.right(90)
enemy.showturtle()
enemy2 = turtle.Turtle()
enemy2.hideturtle()
enemy2.turtlesize(1.3)
enemy2.color('red')
enemy2.fillcolor('red')
enemy2.shape('square')
enemy2.penup()
enemy2.setposition(100, 310)
enemy2.right(90)
enemy2.showturtle()
enemy3 = turtle.Turtle()
enemy3.hideturtle()
enemy3.turtlesize(1.3)
enemy3.color('red')
enemy3.fillcolor('red')
enemy3.shape('square')
enemy3.penup()
enemy3.setposition(200, 310)
enemy3.right(90)
enemy3.showturtle()
enemy4 = turtle.Turtle()
enemy4.hideturtle()
enemy4.turtlesize(1.3)
enemy4.color('red')
enemy4.fillcolor('red')
enemy4.shape('square')
enemy4.penup()
enemy4.setposition(300, 310)
enemy4.right(90)
enemy4.showturtle()
enemy5 = turtle.Turtle()
enemy5.hideturtle()
enemy5.turtlesize(1.3)
enemy5.color('red')
enemy5.fillcolor('red')
enemy5.shape('square')
enemy5.penup()
enemy5.setposition(400, 310)
enemy5.right(90)
enemy5.showturtle()
enemy6 = turtle.Turtle()
enemy6.hideturtle()
enemy6.turtlesize(1.3)
enemy6.color('red')
enemy6.fillcolor('red')
enemy6.shape('square')
enemy6.penup()
enemy6.setposition(-100, 310)
enemy6.right(90)
enemy6.showturtle()
enemy7 = turtle.Turtle()
enemy7.hideturtle()
enemy7.turtlesize(1.3)
enemy7.color('red')
enemy7.fillcolor('red')
enemy7.shape('square')
enemy7.penup()
enemy7.setposition(-200, 310)
enemy7.right(90)
enemy7.showturtle()
enemy8 = turtle.Turtle()
enemy8.hideturtle()
enemy8.turtlesize(1.3)
enemy8.color('red')
enemy8.fillcolor('red')
enemy8.shape('square')
enemy8.penup()
enemy8.setposition(-300, 310)
enemy8.right(90)
enemy8.showturtle()
enemy9 = turtle.Turtle()
enemy9.hideturtle()
enemy9.turtlesize(1.3)
enemy9.color('red')
enemy9.fillcolor('red')
enemy9.shape('square')
enemy9.penup()
enemy9.setposition(-400, 310)
enemy9.right(90)
enemy9.showturtle()
c = turtle.Turtle()
c.hideturtle()

def turn2():
    so.setx(so.xcor() - 8)
def turn():
    so.setx(so.xcor() + 8)
def shoot():
    bullet = turtle.Turtle()
    bullet_list.append(bullet)
    bullet.penup()
    bullet.hideturtle()
    bullet.color('yellow')
    bullet.goto(so.xcor(), so.ycor())
    bullet.shape('circle')
    bullet.showturtle()
    bullet.left(90)

window.onkeypress(turn2, 'Left')
window.onkeypress(turn, 'Right')
window.onkeypress(shoot, 'space')
window.listen()

while True:
    bullets_to_be_removed = []
    enemy.forward(0.18)
    enemy2.forward(0.18)
    enemy3.forward(0.18)
    enemy4.forward(0.18)
    enemy5.forward(0.18)
    enemy6.forward(0.18)
    enemy7.forward(0.18)
    enemy8.forward(0.18)
    enemy9.forward(0.18)
    if so.xcor() > 700:
        so.hideturtle()
        so.setx(-700)
        so.showturtle()
    if so.xcor() < -700:
        so.hideturtle()
        so.setx(700)
        so.showturtle()

    for i in range(len(bullet_list)):
        bullet_list[i].forward(1)
        if bullet_list[i].distance(enemy) < 28:
            enemy.hideturtle()
            enemy.setposition(0, 310)
            enemy.showturtle()
        if bullet_list[i].distance(enemy2) < 28:
            enemy2.hideturtle()
            enemy2.setposition(100, 310)
            enemy2.showturtle()
        if bullet_list[i].distance(enemy3) < 28:
            enemy3.hideturtle()
            enemy3.setposition(200, 310)
            enemy3.showturtle()
        if bullet_list[i].distance(enemy4) < 28:
            enemy4.hideturtle()
            enemy4.setposition(300, 310)
            enemy4.showturtle()
        if bullet_list[i].distance(enemy5) < 28:
            enemy5.hideturtle()
            enemy5.setposition(400, 310)
            enemy5.showturtle()
        if bullet_list[i].distance(enemy6) < 28:
            enemy6.hideturtle()
            enemy6.setposition(-100, 310)
            enemy6.showturtle()
        if bullet_list[i].distance(enemy7) < 28:
            enemy7.hideturtle()
            enemy7.setposition(-200, 310)
            enemy7.showturtle()
        if bullet_list[i].distance(enemy8) < 28:
            enemy8.hideturtle()
            enemy8.setposition(-300, 310)
            enemy8.showturtle()
        if bullet_list[i].distance(enemy9) < 28:
            enemy9.hideturtle()
            enemy9.setposition(-400, 310)
            enemy9.showturtle()

    for j in range(len(bullets_to_be_removed)):
        bullet_list.pop(bullets_to_be_removed[j])

    if enemy.ycor() < -300:
        window.bgcolor('red')
        c.penup()
        c.setposition(-300, 0)
        c.color('black')
        c.pendown()
        c.write('GAME OVER!', font=('arial', 80))
        turtle.done()
    if enemy2.ycor() < -300:
        window.bgcolor('red')
        c.penup()
        c.setposition(-300, 0)
        c.color('black')
        c.pendown()
        c.write('GAME OVER!', font=('arial', 80))
        turtle.done()
    if enemy3.ycor() < -300:
        window.bgcolor('red')
        c.penup()
        c.setposition(-300, 0)
        c.color('black')
        c.pendown()
        c.write('GAME OVER!', font=('arial', 80))
        turtle.done()
    if enemy4.ycor() < -300:
        window.bgcolor('red')
        c.penup()
        c.setposition(-300, 0)
        c.color('black')
        c.pendown()
        c.write('GAME OVER!', font=('arial', 80))
        turtle.done()
    if enemy5.ycor() < -300:
        window.bgcolor('red')
        c.penup()
        c.setposition(-300, 0)
        c.color('black')
        c.pendown()
        c.write('GAME OVER!', font=('arial', 80))
        turtle.done()
    if enemy6.ycor() < -300:
        window.bgcolor('red')
        c.penup()
        c.setposition(-300, 0)
        c.color('black')
        c.pendown()
        c.write('GAME OVER!', font=('arial', 80))
        turtle.done()
    if enemy7.ycor() < -300:
        window.bgcolor('red')
        c.penup()
        c.setposition(-300, 0)
        c.color('black')
        c.pendown()
        c.write('GAME OVER!', font=('arial', 80))
        turtle.done()
    if enemy8.ycor() < -300:
        window.bgcolor('red')
        c.penup()
        c.setposition(-300, 0)
        c.color('black')
        c.pendown()
        c.write('GAME OVER!', font=('arial', 80))
        turtle.done()
    if enemy9.ycor() < -300:
        window.bgcolor('red')
        c.penup()
        c.setposition(-300, 0)
        c.color('black')
        c.pendown()
        c.write('GAME OVER!', font=('arial', 80))
        turtle.done()

    window.update()
